/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyCreatorsRouteImport } from './routes/my-creators'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CUsernameRouteImport } from './routes/c.$username'
import { Route as AccessProductIdRouteImport } from './routes/access.$productId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBecomeCreatorRouteImport } from './routes/_authenticated/become-creator'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as PUsernameSlugRouteImport } from './routes/p.$username.$slug'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api.webhooks.paddle'
import { Route as AuthenticatedDashboardProductsRouteImport } from './routes/_authenticated/dashboard.products'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedDashboardProductsIndexRouteImport } from './routes/_authenticated/dashboard.products.index'
import { Route as AuthenticatedDashboardProductsNewRouteImport } from './routes/_authenticated/dashboard.products.new'

const MyCreatorsRoute = MyCreatorsRouteImport.update({
  id: '/my-creators',
  path: '/my-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CUsernameRoute = CUsernameRouteImport.update({
  id: '/c/$username',
  path: '/c/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessProductIdRoute = AccessProductIdRouteImport.update({
  id: '/access/$productId',
  path: '/access/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBecomeCreatorRoute =
  AuthenticatedBecomeCreatorRouteImport.update({
    id: '/become-creator',
    path: '/become-creator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PUsernameSlugRoute = PUsernameSlugRouteImport.update({
  id: '/p/$username/$slug',
  path: '/p/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardProductsRoute =
  AuthenticatedDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardProductsIndexRoute =
  AuthenticatedDashboardProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardProductsRoute,
  } as any)
const AuthenticatedDashboardProductsNewRoute =
  AuthenticatedDashboardProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/my-creators': typeof MyCreatorsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/access/$productId': typeof AccessProductIdRoute
  '/c/$username': typeof CUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRouteWithChildren
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/p/$username/$slug': typeof PUsernameSlugRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/dashboard/products/': typeof AuthenticatedDashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/my-creators': typeof MyCreatorsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/access/$productId': typeof AccessProductIdRoute
  '/c/$username': typeof CUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/p/$username/$slug': typeof PUsernameSlugRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/my-creators': typeof MyCreatorsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/access/$productId': typeof AccessProductIdRoute
  '/c/$username': typeof CUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/dashboard/products': typeof AuthenticatedDashboardProductsRouteWithChildren
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/p/$username/$slug': typeof PUsernameSlugRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/_authenticated/dashboard/products/': typeof AuthenticatedDashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/library'
    | '/mcp'
    | '/my-creators'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/become-creator'
    | '/dashboard'
    | '/settings'
    | '/access/$productId'
    | '/c/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/products'
    | '/api/webhooks/paddle'
    | '/api/webhooks/stripe'
    | '/p/$username/$slug'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/dashboard/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/library'
    | '/mcp'
    | '/my-creators'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/become-creator'
    | '/settings'
    | '/access/$productId'
    | '/c/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/webhooks/paddle'
    | '/api/webhooks/stripe'
    | '/p/$username/$slug'
    | '/dashboard'
    | '/dashboard/products/new'
    | '/dashboard/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/library'
    | '/mcp'
    | '/my-creators'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/become-creator'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/access/$productId'
    | '/c/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/dashboard/products'
    | '/api/webhooks/paddle'
    | '/api/webhooks/stripe'
    | '/p/$username/$slug'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/products/new'
    | '/_authenticated/dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  McpRoute: typeof McpRoute
  MyCreatorsRoute: typeof MyCreatorsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AccessProductIdRoute: typeof AccessProductIdRoute
  CUsernameRoute: typeof CUsernameRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  PUsernameSlugRoute: typeof PUsernameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-creators': {
      id: '/my-creators'
      path: '/my-creators'
      fullPath: '/my-creators'
      preLoaderRoute: typeof MyCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$username': {
      id: '/c/$username'
      path: '/c/$username'
      fullPath: '/c/$username'
      preLoaderRoute: typeof CUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/$productId': {
      id: '/access/$productId'
      path: '/access/$productId'
      fullPath: '/access/$productId'
      preLoaderRoute: typeof AccessProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/become-creator': {
      id: '/_authenticated/become-creator'
      path: '/become-creator'
      fullPath: '/become-creator'
      preLoaderRoute: typeof AuthenticatedBecomeCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/p/$username/$slug': {
      id: '/p/$username/$slug'
      path: '/p/$username/$slug'
      fullPath: '/p/$username/$slug'
      preLoaderRoute: typeof PUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/products': {
      id: '/_authenticated/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/products/': {
      id: '/_authenticated/dashboard/products/'
      path: '/'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof AuthenticatedDashboardProductsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProductsRoute
    }
    '/_authenticated/dashboard/products/new': {
      id: '/_authenticated/dashboard/products/new'
      path: '/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof AuthenticatedDashboardProductsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardProductsRoute
    }
  }
}

interface AuthenticatedDashboardProductsRouteChildren {
  AuthenticatedDashboardProductsNewRoute: typeof AuthenticatedDashboardProductsNewRoute
  AuthenticatedDashboardProductsIndexRoute: typeof AuthenticatedDashboardProductsIndexRoute
}

const AuthenticatedDashboardProductsRouteChildren: AuthenticatedDashboardProductsRouteChildren =
  {
    AuthenticatedDashboardProductsNewRoute:
      AuthenticatedDashboardProductsNewRoute,
    AuthenticatedDashboardProductsIndexRoute:
      AuthenticatedDashboardProductsIndexRoute,
  }

const AuthenticatedDashboardProductsRouteWithChildren =
  AuthenticatedDashboardProductsRoute._addFileChildren(
    AuthenticatedDashboardProductsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProductsRoute: typeof AuthenticatedDashboardProductsRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardProductsRoute:
      AuthenticatedDashboardProductsRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBecomeCreatorRoute: typeof AuthenticatedBecomeCreatorRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBecomeCreatorRoute: AuthenticatedBecomeCreatorRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  McpRoute: McpRoute,
  MyCreatorsRoute: MyCreatorsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AccessProductIdRoute: AccessProductIdRoute,
  CUsernameRoute: CUsernameRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  PUsernameSlugRoute: PUsernameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
